/// <reference types="node" />
import { expect, test } from '@grafana/plugin-e2e';
import { type Locator, type Page, type Response } from '@playwright/test';

const DS_NAME = process.env.DS_INSTANCE_NAME || 'zipkin';
const DS_UID = 'zipkin-e2e';

// Trace IDs match those generated by the zipkin-loader service in
// docker-compose.yaml. Keep in sync with tests/e2e/fixtures/.
const FRONTEND_TRACE_ID = '1111111111111111';
const BACKEND_TRACE_ID = '2222222222222222';

// Zipkin's default in-memory store has a finite retention window, so the
// loader generates fixture spans with `now`-relative timestamps. Compute the
// query window once at module load time so every test in this run uses the
// same range. A 2 h lookback comfortably contains the just-loaded fixtures.
const DYNAMIC_TO_ISO = new Date().toISOString();
const DYNAMIC_FROM_ISO = new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString();

// Grafana 13 migrated query editor row selectors from aria-label to data-testid
// (https://github.com/grafana/grafana/pull/121784). This helper matches both
// shapes so tests work across versions until @grafana/plugin-e2e ships a fix
// and this repo upgrades.
function getQueryEditorRow(page: Page, refId: string): Locator {
  return page
    .locator('[data-testid="data-testid Query editor row"], [aria-label="Query editor row"]')
    .filter({
      has: page.locator(
        `[data-testid="data-testid Query editor row title ${refId}"], [aria-label="Query editor row title ${refId}"]`
      ),
    });
}

// Builds an Explore URL with a Zipkin trace-id query pre-encoded in the panes
// parameter. Uses the computed ISO timestamps so the query lands within the
// loaded fixture window.
function exploreUrl(traceID: string): string {
  const panes = JSON.stringify({
    explore: {
      datasource: DS_UID,
      queries: [
        {
          refId: 'A',
          query: traceID,
          queryType: 'traceID',
          datasource: { type: 'zipkin', uid: DS_UID },
        },
      ],
      range: { from: DYNAMIC_FROM_ISO, to: DYNAMIC_TO_ISO },
    },
  });
  return `/explore?orgId=1&schemaVersion=1&panes=${encodeURIComponent(panes)}`;
}

// Waits for the first /api/ds/query response where results.A has frames.
// response.json() must be called inside the predicate while the CDP body
// reference is still valid; calling it after the await fails intermittently
// with "No resource with given identifier found".
async function waitForMainQueryResponse(page: Page): Promise<{ response: Response; body: any }> {
  let body: any;
  const response = await page.waitForResponse(async (r: Response) => {
    if (!r.url().includes('/api/ds/query') || !r.ok()) {
      return false;
    }
    const b = await r.json().catch(() => null);
    if (!Array.isArray(b?.results?.A?.frames)) {
      return false;
    }
    body = b;
    return true;
  });
  return { response, body };
}

test.describe('Query editor', () => {
  test.beforeEach(async ({ explorePage }) => {
    // explorePage.goto() is called by the fixture before this hook runs.
    // Zipkin is provisioned as the default - datasource.set() confirms the
    // selection without firing a new query (Grafana treats it as a no-op when
    // unchanged).
    await explorePage.datasource.set(DS_NAME);
  });

  test.describe('rendering', () => {
    test(
      'smoke: renders query type controls',
      { tag: '@plugins' },
      async ({ explorePage, page }) => {
        // Cascader fetches the service list on mount. Mock it so the smoke
        // test does not depend on the backend reachable from inside Grafana.
        await explorePage.mockResourceResponse('services', []);
        const queryRow = getQueryEditorRow(page, 'A');
        await expect(queryRow.getByText('Query type', { exact: true })).toBeVisible();
        await expect(queryRow.getByRole('radio', { name: 'TraceID' })).toBeVisible();
        await expect(queryRow.getByRole('radio', { name: 'TraceID' })).toBeChecked();
        await expect(queryRow.getByRole('button', { name: 'Import trace' })).toBeVisible();
        await expect(queryRow.getByRole('button', { name: 'Traces' })).toBeVisible();
      }
    );

    test('renders trace id input', async ({ explorePage, page }) => {
      await explorePage.mockResourceResponse('services', []);
      const queryRow = getQueryEditorRow(page, 'A');
      // The QueryField is a multi-line contenteditable; use role=textbox
      await expect(queryRow.getByRole('textbox')).toBeVisible();
    });

    test('opens import trace modal', async ({ explorePage, page }) => {
      await explorePage.mockResourceResponse('services', []);
      const queryRow = getQueryEditorRow(page, 'A');
      await queryRow.getByRole('button', { name: 'Import trace' }).click();
      const modalHeading = page.getByRole('heading', { name: 'Upload trace' });
      await expect(modalHeading).toBeVisible();
      // Dismiss with Escape rather than clicking the X icon — on Grafana 12.3.x
      // a substring match of `name: 'Close'` also matches the mega-menu's
      // "Close menu" button. Escape works across all versions.
      await page.keyboard.press('Escape');
      await expect(modalHeading).toBeHidden();
    });
  });

  test.describe('query execution', () => {
    test('executes a trace id query and receives OK response', async ({ explorePage, page }) => {
      // Mock the trace response so this test does not depend on the backend
      // being reachable. The smoke contract here is "the editor fires a
      // /api/ds/query when a trace id is encoded in the URL".
      await explorePage.mockQueryDataResponse({ results: { A: { frames: [] } } });
      await explorePage.mockResourceResponse('services', []);
      const responsePromise = page.waitForResponse((resp) => resp.url().includes('/api/ds/query'));
      await page.goto(exploreUrl(FRONTEND_TRACE_ID));

      const response = await responsePromise;
      expect(response.ok()).toBe(true);
    });
  });
});

// These tests use real fixture data loaded by the zipkin-loader service in
// docker-compose.yaml. Each navigates to an Explore URL with a known trace
// id pre-encoded in the panes parameter and asserts on the response shape.
test.describe('Query editor with fixture data', () => {
  // Serialize fixture-data tests so they don't compete for the shared Zipkin
  // instance and produce slow responses that look like failures.
  test.describe.configure({ mode: 'serial' });

  test.describe('frontend trace', () => {
    test(`returns 3 spans for trace ${FRONTEND_TRACE_ID}`, async ({ page }) => {
      const responsePromise = waitForMainQueryResponse(page);
      await page.goto(exploreUrl(FRONTEND_TRACE_ID));
      const { response, body } = await responsePromise;
      expect(response.ok()).toBe(true);
      expect(body.results?.A?.error).toBeUndefined();
      expect(body.results?.A?.frames?.length).toBeGreaterThan(0);

      // The trace frame has a `data.values` row per span. The first field is
      // traceID, the fourth is operationName.
      const frame = body.results.A.frames[0];
      expect(frame.data.values[0].length).toBe(3);
      expect(frame.data.values[3]).toEqual(expect.arrayContaining(['get /api/users', 'db-query', 'cache-lookup']));
    });

    test('renders trace view header with service name', async ({ page }) => {
      await page.goto(exploreUrl(FRONTEND_TRACE_ID));
      // Wait for the trace frame to arrive before asserting on the rendered view.
      await waitForMainQueryResponse(page);
      await expect(page.getByRole('heading', { name: /^frontend:/, level: 1 })).toBeVisible();
    });
  });

  test.describe('backend trace', () => {
    test(`returns 1 span for trace ${BACKEND_TRACE_ID}`, async ({ page }) => {
      const responsePromise = waitForMainQueryResponse(page);
      await page.goto(exploreUrl(BACKEND_TRACE_ID));
      const { response, body } = await responsePromise;
      expect(response.ok()).toBe(true);
      expect(body.results?.A?.error).toBeUndefined();
      expect(body.results?.A?.frames?.length).toBeGreaterThan(0);

      const frame = body.results.A.frames[0];
      expect(frame.data.values[0].length).toBe(1);
      expect(frame.data.values[3]).toEqual(['process-order']);
    });
  });
});
