name: Scheduled Cloud end-to-end tests

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  playwright-cloud:
    uses: grafana/data-sources-ci-workflows/.github/workflows/playwright-cloud.yml@439d34f6c2b178a759327df1ab7182e0ed63ac09 # main
    secrets: inherit
    with:
      repo-secrets: |
        DS_INSTANCE_NAME=ci/data/data-sources/grafana-zipkin-datasource/zipkin:name
        DS_INSTANCE_URL=ci/data/data-sources/grafana-zipkin-datasource/zipkin:url
